// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5YpmSbVwe3xGvoMlES7eC1ucvXYP3JZ8',
    appId: '1:551054105996:web:9ff1b2f89b00a8c2598aa9',
    messagingSenderId: '551054105996',
    projectId: 'colombiatourist-eaeee',
    authDomain: 'colombiatourist-eaeee.firebaseapp.com',
    storageBucket: 'colombiatourist-eaeee.appspot.com',
    measurementId: 'G-LJBSSYB58L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKnvGubyPMlIzw3SYnElU_O7kMEnNGioo',
    appId: '1:551054105996:android:e61b24decc64a276598aa9',
    messagingSenderId: '551054105996',
    projectId: 'colombiatourist-eaeee',
    storageBucket: 'colombiatourist-eaeee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAofmfR-_QWbTD_lUUkIgOyHeqkBx1vGqc',
    appId: '1:551054105996:ios:a0f8ca0e4eb7cc7f598aa9',
    messagingSenderId: '551054105996',
    projectId: 'colombiatourist-eaeee',
    storageBucket: 'colombiatourist-eaeee.appspot.com',
    iosClientId: '551054105996-mgfsfh0v0hj3ruempb5nf26k3mile9h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMascotas',
  );
}
